### ISSUE TITLE
Ensure consistent-hashing gives the same results as Graphite's implementation

### ISSUE THREAD

**Issue by jamiealquiza** [jamiealquiza/polymur#11]

**Comment by blysik** [comment]
With this change, will polymur's hashing be identical to carbon's?

**Comment by jamiealquiza** [comment]
I haven't read carbon's internals on that bit, but I'd say it would be ideal to operationally mirror it for users sake

**Comment by jamiealquiza** [comment]
Graphite-web's CARBONLINK_HOSTS uses CH to route queries to Carbon-cache daemons to fetch inflight queries that weren't found on-disk. Polymur is using a different CH algo, so cached queries aren't where Graphite-web is expecting the, causing recent data points to be unreadable.

**Comment by jamiealquiza** [comment]
Under way in the following branch https://github.com/jamiealquiza/polymur/tree/consistent-hashing

**Comment by jamiealquiza** [comment]
closed in https://github.com/jamiealquiza/polymur/commit/95aa409c1f2b23edfb1c174458b3a73121594063
