### ISSUE TITLE
log verbosity

### ISSUE THREAD

**Issue by ngamber** [jamiealquiza/polymur#52]
Would be nice to have configurable log levels, in a relatively unused system we're seeing 100MB+/hr  of logs that are just 
...sending batch
... batch received

would be nice to lower it down to just warnings or errors.

**Comment by jamiealquiza** [comment]
Recent change adds `-verbose` flag to polymur-proxy (defaults to `true` as to not impact existing, default behavior) that currently defines whether or not non-error batch info is logged

**Comment by jamiealquiza** [comment]
Closing with interim fix until logging rewritten
