### ISSUE TITLE
Queues capacity

### ISSUE THREAD

**Issue by rattlehead12** [jamiealquiza/polymur#53]
Running 
`root@debian27:# ./polymur -destinations="127.0.0.1:2103,127.0.0.1:2203,127.0.0.1:2303" -metrics-flush=30 -"listen-addr=0.0.0.0:2003" -distribution="hash-route" `

And in the output i get something like this

`
2017/03/24 05:36:08 Last 5.00s: Received 180 data points | Avg: 36.00/sec.

2017/03/24 05:36:13 Last 5.00s: Received 308 data points | Avg: 61.60/sec.

2017/03/24 05:36:18 Last 5.00s: Received 329 data points | Avg: 65.80/sec.

2017/03/24 05:36:18 Destination 127.0.0.1:2303 queue length: 54

2017/03/24 05:36:18 Destination 127.0.0.1:2203 queue length: 21

2017/03/24 05:36:18 Destination 127.0.0.1:2103 queue length: 40

2017/03/24 05:36:23 Last 5.00s: Received 377 data points | Avg: 75.40/sec.

2017/03/24 05:36:23 Destination 127.0.0.1:2303 queue length: 32

2017/03/24 05:36:23 Destination 127.0.0.1:2203 queue length: 15

2017/03/24 05:36:23 Destination 127.0.0.1:2103 queue length: 16

2017/03/24 05:36:28 Last 5.00s: Received 285 data points | Avg: 57.00/sec.
`
in fact, i really lose many data points,
i have been looink in the log file of my cache instances and i get just a few points in comparison with the receiveds points

**Comment by jamiealquiza** [comment]
Hi,

Both polymur and carbon cache report a metric for the number of data points received. Can you get a graph of that so we can compare?

**Comment by jamiealquiza** [comment]
Feel free to respond/re-open if this is still an issue.

Thanks!
