### ISSUE TITLE
Missing License file

### ISSUE THREAD

**Issue by tehlers320** [jamiealquiza/polymur#60]
I see the license in the code, but it could use a license file in general.

**Comment by jamiealquiza** [comment]
I've been crawling my repos with licenses baked into the code and breaking it out - will update this soon.

**Comment by jamiealquiza** [comment]
License / linting in https://github.com/jamiealquiza/polymur/tree/lint-license

**Comment by jamiealquiza** [comment]
Feel free to open more issues / comments re: this or anything else you spot. I've been planning on reviving development on this project and it's always great to see user input!

**Comment by tehlers320** [comment]
Thanks, i actually have one i just found on polymur-proxy.
